# Generated by Django 3.2 on 2024-01-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost_of_currency',
            name='value',
            field=models.CharField(max_length=7),
        ),
    ]
