# Generated by Django 3.2 on 2024-01-24 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_rate', '0004_alter_cost_of_currency_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost_of_currency',
            options={'ordering': ['-date']},
        ),
    ]
